### ISSUE TITLE
iphone-tv.eu

### ISSUE THREAD

**Issue by allouch89** [allouch89/ShaniXBMCdatabase#2]
Can anyone help me get the Auth token from this website (http://en.iphone-tv.eu)?
You can make an example with this channel: http://en.iphone-tv.eu/stream/de/35
Today, the Auth is "bf4c6448fae10ee77e39b8b435cfab4747f8ed20833e1d427f8b19730deca7c1", but i would like to be able to get that automatic, i will be using php, but if you can get it done with xbmc thats fine too, this token I got manually by monitoring the headers from the page.
The full link today, is: http://ipm.iphone-tv.eu:1345/Live/Auth:bf4c6448fae10ee77e39b8b435cfab4747f8ed20833e1d427f8b19730deca7c1/Channel:disneychannel/playlist.m3u8
They change the auth token every day. I'd appreciate the help.
The reason that i am asking here is because you guys are experts in this kinda stuff, especially @Shani-08, im still pretty new at extracting stuff from website.

**Comment by allouch89** [comment]
Just a note, a few weeks ago, there was only german channels in there. Now they have added alot more, including turkish channels, it wont surprise me if they are going to add arabic channels aswell. In that case, the work on this can be useful for the plugin aswell.

**Comment by hassuni** [comment]
@allouch89  I have a regex for it.
I can send it to u per email, or PM in kodi http://forum.kodi.tv/index.php or http://forums.tvaddons.ag

**Comment by allouch89** [comment]
You can send it my email; allouch @ live . dk

**Comment by hassuni** [comment]
done, need time to start

**Comment by allouch89** [comment]
Thanks but, which one is for the Auth token? because i am going to use php to get it.

**Comment by hassuni** [comment]
what sended to u is one channel you can play it with livestreampro

**Comment by hassuni** [comment]
install livestreampro addon  from shani repo,if you dont have it

**Comment by allouch89** [comment]
Its just that I am not going to use xbmc/kodi to watch the streams

**Comment by allouch89** [comment]
I am so close, but i keep getting some kind of fake Auth token

**Comment by allouch89** [comment]
http://onlinebotservices.com/test/?id=35
Maybe you can help me figure out what im missing?

**Comment by allouch89** [comment]
I see that the iphone-tv urls aint working in shahid too, i guess they have updated their security

**Comment by Shani-08** [comment]
They did a small change for which Shahid and LSpro won't work. I have pushing the change which will allow LSpro to work but with different regex, same for Shahid.

**Comment by Shani-08** [comment]
@allouch89 @zombiB @hassuni 
I have updated LSPro so download 1.5.7
Please see this post http://forums.tvaddons.ag/threads/24190-Release-LiveStreamsPro?p=253984&viewfull=1#post253984 to know how to write the format.
For Shahid, click download and update your file to use the correct format.

**Comment by allouch89** [comment]
@Shani-08 could you help me by poiting out what i am missing in this page http://onlinebotservices.com/test/?id=35 ?
I see you try to extract something from the javascript line, but im lost in regex so i cant really figure what is it exactly.

**Comment by allouch89** [comment]
I still cant get iphone-tv links to work, and i cant find the links anywhere to try to edit to the new format

**Comment by Shani-08** [comment]
@allouch89 use your local file and my regex against some channel and try to play, Make sure you click the download button so that you get the code.

**Comment by Shani-08** [comment]
I can't see you php code but whatever you are doing, you are getting a dummy page back, I am parsing their web page and translating like a browser would do.

**Comment by allouch89** [comment]
You can see what i am doing here:

**Comment by allouch89** [comment]
I am getting the exact same page back, just not the same result from the decoded line. I am missing the headers right?

**Comment by Shani-08** [comment]
seems like user agent or something, i can't see that on my pc as php is calling the page server side.

**Comment by allouch89** [comment]
I just tried with user-agent, didnt help.

**Comment by allouch89** [comment]
i have tried with curl aswell and adding headers with user-agent etc., nothing is working.
im just gonna give up for now.

**Comment by Shani-08** [comment]
Just try LSPro or Shahid like I said. At least you see it working and compare what's wrong.

**Comment by allouch89** [comment]
I have tried with LSPro and it works like a charm, good job with that.
However, i need to be able to do it with php and its not working in anyway i have tried :(
I have tried with all sort of headers, useragents and even cookiejar, and with different 3 methods; file_get_contents, curl and fsockopen. Oh well, i guess im giving up on this one.

**Comment by allouch89** [comment]
Just one last thing @Shani-08 : Is it the "def getUrl" function you use with the get-first regex?
I cant really figure out where its handled in the default.py player in LSPro.

**Comment by allouch89** [comment]
I guess you got tired of this issue :) anyway thanks for helping.
