### ISSUE TITLE
Help with "Universal Somali"

### ISSUE THREAD

**Issue by yusha1439** [allouch89/ShaniXBMCdatabase#21]
Hello and Salaam,
I've been trying to get the Livestream.com source to work for Universal Somali channel but still having trouble.
<cname>Universal Somali</cname>
 <item>
 <title>low2</title>
 <link>$doregex[get-page]$doregex[get-initsesion]|Cookie=$get_cookies$&amp;User-Agent=iPhone</link>
 <regex>
 <name>get-initsesion</name>
 <expres></expres>
 <page>$doregex[get-page]</page>
 <agent>iPhone</agent>
 <cookieJar></cookieJar>
 </regex>
 <regex>
 <name>get-page</name>
 <expres>"rtsp_url":"(.*?)"</expres>
 <page>http://livestream.com/accounts/2058831/events/2072662/</page>
 <agent>iPhone</agent>
 <cookieJar></cookieJar>
 </regex>
 </item>
</streaminginfo>
This Code gets the rtsp url for the channel, but playback is horrible. It freezes, stutters, then closes. 
I tried <expres>"mu8_url":"(.*?)"</expres>
but it just plays a pre-recorded program.
If I use my Galaxy s4, and go to 
http://livestream.com/accounts/2058831/events/2072662/player?width=480&height=300&autoPlay=true&mute=false
Click Play, I get:
http://api.new.livestream.com/accounts/2058831/events/2072662/broadcasts/93469179.m3u8?dw=100&hdnea=st=1437338750~exp=1437339650~acl=/i/2058831_2072662_5a2564db_1@143337/*~hmac=de859306d7266c489d95c4807a5802160b4bb5e66c9284dda18660312a656a07
and then I can open this in MXplayer, or native android player, and it gives me a smooth playback from m3u8 source.
looking at the api at: http://api.new.livestream.com/accounts/2058831/events/2072662
I can find the m3u8 playback, but its at the bottom of the page and its one in 14 matches.  I've tried re-arranging the xml code in every way I can think of, and the only other thing I've thought of is to just manually get and input the rtmp url everyday but thats really tedious... I appreciate any and all help on this

**Comment by hassuni** [comment]
try this one
http://livestream-f.akamaihd.net/i/2058831_2072662_5a2564db_1@143337/index_446_av-p.m3u8?sd=10&amp;dw=100&amp;rebase=on|Cookie=hdntl%3Dexp%3D1437494668%7Eacl%3D%252fi%252f2058831_2072662_5a2564db_1%2540143337%252f%2A%7Edata%3Dhdntl%7Ehmac%3Da727a1a3a638c2dae804ce9fccf34fd20b90b98e51d08e92bb314cee93be834e%3B%20path%3D/%3B%20domain%3Dlivestream-f.akamaihd.net%3B%2C%20_alid_%3D27OgurVD8AsB/jWr1eDT/Q%3D%3D%3B%20path%3D/i/2058831_2072662_5a2564db_1%40143337/%3B%20domain%3Dlivestream-f.akamaihd.net&amp;User-Agent=Mozilla/5.0 (iPhone; CPU iPhone OS 8_3 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12F70 Safari/600.1.4

**Comment by yusha1439** [comment]
How exactly to add it to the xml?

**Comment by hassuni** [comment]
http://pastebin.com/RaPJs7dv

**Comment by yusha1439** [comment]
Link says the paste was removed
