### ISSUE TITLE
Links for African channels

### ISSUE THREAD

**Issue by yusha1439** [allouch89/ShaniXBMCdatabase#24]
Hi to everyone,
Sorry to bother. I recently came across a website http://axadledirect.com That has all of the somali channels streaming except 2. I've been trying to figure out how to get it into the xml, but so far I've been unsuccessful. I'm posting here if anyone else maybe could figure it out. 
Attached is one of the html pages, I was able to capture it using mozilla tools but as there is some sort of key or pass generated with each visit to the webpage, the file would only connect and play the stream once. If anyone has any ideas it would be appreciated, and a big development for African Channels. Here is the html for SNTV Page: http://pastebin.com/dyNQg5L5

**Comment by yusha1439** [comment]
Sorry to Bump, any ideas? Anyone?

**Comment by allouch89** [comment]
All channels seems to be offline right now

**Comment by yusha1439** [comment]
That's due to GLARAB server patch, I'm not sure if they have found a solution yet to that. What I posted here was an idea to somehow get the links from the above mentioned website http://axadledirect.com/

**Comment by yusha1439** [comment]
I just tried Shani repo and looks like it was taken down. Better save copies of the code

**Comment by allouch89** [comment]
I was also refering to that website, when i said "All channels seems to be offline right now".
They were literally all down, on the website http://axadledirect.com/ when i checked.
I will look into the website and see if there is a way.

**Comment by yusha1439** [comment]
Also, what is the fix for shahid Arabic addon? File download isn't working
and it's only scanning old files

**Comment by allouch89** [comment]
You have to update the addon then, install the shani repo and it will update itself

**Comment by zombiB** [comment]
old issue i am closing it
