### ISSUE TITLE
filmon url for SNTV

### ISSUE THREAD

**Issue by yusha1439** [allouch89/ShaniXBMCdatabase#29]
I've been looking everywhere for the filmon url xml but cannon find it. Under Shahid arabic addon, Africa category, Channel SNTV only has teledunet listed as a working source and it sucks. I found that "somali channel" (which was bought out by somali cable btw) has a listed source for filmon url- which is actually SNTV (Somali National TV). I would make an edit and pull request, but I cannot find the xml anywhere. Please if someone can edit- thanks in advance.

**Comment by Shani-08** [comment]
both xmls are here now edit away!
