### ISSUE TITLE
new source for "Moga Comedy"

### ISSUE THREAD

**Issue by emadmahdi** [allouch89/ShaniXBMCdatabase#49]
Moga Comedy ... https://www.arablive-tv.com/?vid=63
.
i am unable to get the link from this url ... i wonder if someone can help ??
.
i know it is similar to the link below but i don't know how to get the variables sig= & e=
.
rtmp://iptv.arablive-tv.com/live/moga?e=1457339964&sig=DADAjVs-kXUenPDGk1LzjA swfUrl=https://www.arablive-tv.com/wp-content/plugins/contus-video-gallery/hdflvplayer/hdplayer.swf pageUrl=https://www.arablive-tv.com/?vid=63

**Comment by hassuni** [comment]
i get this one by using url helper and I think that need regex for e and sig
rtmp://iptv.arablive-tv.com/live<playpath>moga?e=1460307082&sig=A09ZxcMUNFkE0NKLGfJUww <swfUrl>https://www.arablive-tv.com/wp-content/plugins/contus-video-gallery/hdflvplayer/hdplayer.swf <pageUrl>https://www.arablive-tv.com/?vid=63
rtmp://iptv.arablive-tv.com/live<playpath>moga?e=1460307094&sig=dUwcduZyPpDjhRsZaliGLg <swfUrl>https://www.arablive-tv.com/wp-content/plugins/contus-video-gallery/hdflvplayer/hdplayer.swf <pageUrl>https://www.arablive-tv.com/?vid=63

**Comment by emadmahdi** [comment]
i also used url helper and i got the same link ... then i checked the tcp packets using a sniffer ... and i also tried to use regex but i found that the page is not returning any sig= or e= to be captured by regex ... I feel the problem is more related to the secure http (https) which communicate using unreadable encoded data ... or may be it needs a special plugin that can do this kind of communication.

**Comment by allouch89** [comment]
http://hls.arablive-tv.com/moga/index.m3u8

**Comment by emadmahdi** [comment]
Thanks for the link ... But this link does not work without accessing the same channel from it's own website ... so i was wondering how to access the html page before playing the link ... i know it can be done using regex ... but is there a way to do this without using a regex ?? ... i mean doing something like this :

<page>https://www.arablive-tv.com/?vid=63</page>
<link>http://hls.arablive-tv.com/moga/index.m3u8</link>

**Comment by allouch89** [comment]
Try it again tommorow , it works with accessing the page

**Comment by allouch89** [comment]
It works again now

**Comment by emadmahdi** [comment]
should i use < page > inside < item > or inside < streaminginfo > ??

**Comment by allouch89** [comment]
Im guessing inside < item > but i dont know, thats why i dont add this kind of streams.
however,  you can just add the m3u8 link without the page info

**Comment by emadmahdi** [comment]
this m3u8 link does not work without calling the https page ... and if the https page was called from internet explorer then the m3u8 link will work for less than an hour and then will stop working again.

**Comment by emadmahdi** [comment]
I tried < page > ... both inside < item > and outside < item > and none of them worked ... any ideas before going to use < regex > as I think regex usually cause a delay and need more processing and not only accessing a page.

**Comment by allouch89** [comment]
well the link is working for me just fine, without accessing the website
