### ISSUE TITLE
iFilm Series

### ISSUE THREAD

**Issue by emadmahdi** [allouch89/ShaniXBMCdatabase#67]
Hello Everyone ...

I was wondering if it is possible to add iFilm series to Shahid Add-on ??!!!!!

Here is some details and examples ...

1- It is available in three languages Arabic, English, and Farsi
2- The series name and the language are presented as two letters and a number in the folder before the mp4 filename
3- The mp4 filename consists from the episode number and the resolution

ARABIC
http://ifilmtv.ir/arabic/series/
http://ifilmtv.ir/Arabic/Serie/30914/
SD	   http://93.190.24.111:82/Ar30914/2_320.mp4
HD	   http://93.190.24.111:82/Ar30914/2.mp4

ENGLISH
http://ifilmtv.ir/english/series/
http://ifilmtv.ir/English/Serie/197/
SD	   http://93.190.24A.111:82/En197/2_320.mp4
HD	   http://93.190.24.111:82/En197/2.mp4

FARSI
http://ifilmtv.ir/farsi/series/
http://ifilmtv.ir/Farsi/Serie/267/
SD	   http://93.190.24.111:82/267/2_320.mp4
HD	   http://93.190.24.111:82/267/2.mp4

**Comment by Shani-08** [comment]
looks easy, where is the episodes list?

**Comment by Shani-08** [comment]
don't worry, its working now, if you click download files. i have only added arabic series at the moment.

**Comment by emadmahdi** [comment]
Thank you Shani ... You are the best ... i wonder if you can add an option to play SD or HD because I think the iFilm server is buffering when using HD ...

**Comment by Shani-08** [comment]
now the default is SD and if you want HD then use the Misc settings area to turn on the option. click download files if you dont see the settings.

**Comment by emadmahdi** [comment]
Thanks Shani ...
@Shani-08 👍 👍 👍 👍 👍 ...

**Comment by emadmahdi** [comment]
just one thing ... I noticed that the HD setting does not apply immeidatly ... it needs ...

1- change the setting
2- close the add-on
3- open the add-on again
4- HD streaming will start to work

is this normal or it can be applied immediately !!!!

**Comment by Shani-08** [comment]
if you are on the listing already then it has already read the settings. if you now change it then you have to go one step back and come back again.

**Comment by emadmahdi** [comment]
yes it is working with one step back ... thank you ...

**Comment by emadmahdi** [comment]
Hi Shani ... the ifilm series is not working now ... they changed the hostname ... I think they use temporary hostnames for website development ... anyways if you use the IP instead of the hostname then it will work normally again ... you can use this IP ... 93.190.24.111 ... I already tested on your script and it did work ... thanks

**Comment by emadmahdi** [comment]
Hi Shani,

ifilm series titles list is missing the first 7 titles (the current playing series) ... for these 7 titles they actually used ... <img> & <div> ... instead of ... <span> & <img> ...

Thanks

**Comment by emadmahdi** [comment]
Will you please add these 7 missing iFilm series titles in the begging of the list not at the end because these are the current live titles that is currently playing.

**Comment by emadmahdi** [comment]
Hi Shani,
in my kodi installation i duplicated line 763 of the file "default.py" and modifid it to get the missing 7 titles ... but I do not know how to submit this as a change request for this file ... so i was wondering if there is a way to submit these kind of changes to this file ??!!!!!!

these are the two lines that i used to replace the original line 763:

`
       match =re.findall('<li>\s*<a href="(.*?)".*\s*.*\s*.*?class=\'title\'>(.*?)<.*?\s*<div class=\'(.*?)\'', link, re.UNICODE)
       match +=re.findall('<li>\s*<a href="(.*?)".*\s*.*\s*.*?class=\'title\'>(.*?)<.*?\s*<img src="(.*?)"', link, re.UNICODE)
`

**Comment by Shani-08** [comment]
thanks, its now on the server and next refresh should take it
